resources:
  - name: maven-spring
    type: git 
    source: 
      uri: https://github.com/ahmadjubair33/spring-boot-example.git
      branches: master
  -  name: depen
     type: docker-image
     source: 
        repository: maven 
        tag: 3.6.0-jdk-8-alpine
jobs:
- name: maven-job
  plan:
  - get: maven-spring
  - get: depen
    trigger: true
  - task: mvn-test
    image: depen
    config:
      inputs:
      - name: maven-spring
      outputs:
      - name: mvn-output
      platform: linux
      run:
        path: mvn
        args:
            - clean 
            - test
            - package
            - -f
            - maven-spring/pom.xml
            
